#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
	configure)
		/usr/share/metis-dkms/scripts/post-install.sh
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0
