#ifndef __METIS_VERSION_H__
#define __METIS_VERSION_H__

// -----------------------------------------------------------------
// This is an autogenerated file. DO NOT EDIT MANUALLY!
// -----------------------------------------------------------------

#define DRIVER_VERSION "1.4.4"

#endif /* __METIS_VERSION_H__ */
